# Generated by Django 4.1.5 on 2023-04-13 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.CharField(max_length=200, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customervehicle_name', models.CharField(max_length=200)),
                ('plate_number', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
                ('entry_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('total_spaces', models.IntegerField()),
                ('available_space', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_paid', models.BooleanField(default=False)),
                ('Customervehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customervehicle')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkinglot')),
                ('parking_reservation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='parkingapp.parkingreservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.BigIntegerField()),
                ('cardholder_name', models.CharField(max_length=200)),
                ('expiration_date', models.DateField()),
                ('is_default', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parkingapp.customerprofile')),
            ],
        ),
    ]
