# Generated by Django 4.1.4 on 2023-03-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
